# Generated by Django 2.2.1 on 2019-06-20 01:18

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassCathegory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ContactType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_date', models.DateField()),
                ('income_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=200)),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=18)),
                ('quantity', models.IntegerField(default=1)),
                ('keep_inventory', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('order', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('email', models.EmailField(max_length=254)),
                ('address_number', models.IntegerField(verbose_name='number')),
                ('address_street', models.CharField(max_length=200, verbose_name='street')),
                ('address_complement', models.CharField(blank=True, max_length=200, null=True)),
                ('address_zip_code', models.CharField(max_length=6)),
                ('address_city', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact', to='taekonline.Student')),
                ('contact_type', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='taekonline.ContactType')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='taekonline.Student')),
            ],
        ),
        migrations.CreateModel(
            name='RankHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_date', models.DateTimeField()),
                ('rank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='taekonline.Rank')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='taekonline.Student')),
            ],
        ),
        migrations.CreateModel(
            name='IncomeProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('profit', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('income', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taekonline.Income')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taekonline.Product')),
            ],
        ),
        migrations.AddField(
            model_name='income',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='taekonline.Student'),
        ),
        migrations.CreateModel(
            name='ClassAgenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('sunday', models.BooleanField(default=False)),
                ('monday', models.BooleanField(default=False)),
                ('tuesday', models.BooleanField(default=False)),
                ('wednesday', models.BooleanField(default=False)),
                ('thursday', models.BooleanField(default=False)),
                ('friday', models.BooleanField(default=False)),
                ('saturday', models.BooleanField(default=False)),
                ('cathegory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='taekonline.ClassCathegory')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_date', models.DateTimeField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='taekonline.Student')),
            ],
        ),
    ]
