# Generated by Django 2.2.1 on 2019-06-02 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taekonline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcontact',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact', to='taekonline.Student'),
        ),
        migrations.AlterField(
            model_name='studentcontact',
            name='contact_type',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='taekonline.ContactType'),
        ),
    ]
