# Generated by Django 2.2.1 on 2019-06-12 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taekonline', '0003_auto_20190602_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentcontact',
            name='order',
        ),
        migrations.AlterField(
            model_name='student',
            name='address_number',
            field=models.IntegerField(verbose_name='number'),
        ),
        migrations.AlterField(
            model_name='student',
            name='address_street',
            field=models.CharField(max_length=200, verbose_name='street'),
        ),
    ]
