# Generated by Django 2.2.1 on 2019-06-12 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taekonline', '0004_auto_20190612_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcontact',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
