# Generated by Django 2.2.1 on 2019-06-12 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taekonline', '0005_studentcontact_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RankHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_date', models.DateField()),
                ('rank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='taekonline.Rank')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='taekonline.Student')),
            ],
        ),
    ]
