# Generated by Django 2.2.1 on 2019-06-13 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taekonline', '0007_rank_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='rakings',
            field=models.ManyToManyField(related_name='rankings', through='taekonline.RankHistory', to='taekonline.Rank'),
        ),
    ]
