# Generated by Django 2.2.1 on 2019-06-13 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taekonline', '0008_student_rakings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='rakings',
            new_name='rankings',
        ),
    ]
