# Generated by Django 2.2.1 on 2019-06-16 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taekonline', '0010_auto_20190614_2249'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_date', models.DateTimeField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='taekonline.Student')),
            ],
        ),
    ]
