# Generated by Django 2.2.1 on 2019-06-16 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taekonline', '0011_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rankhistory',
            name='exam_date',
            field=models.DateTimeField(),
        ),
    ]
