# Generated by Django 2.2.1 on 2019-06-16 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taekonline', '0013_auto_20190616_0344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classagenda',
            old_name='class_cathegory',
            new_name='cathegory',
        ),
    ]
