# Generated by Django 2.2.1 on 2019-06-18 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taekonline', '0014_auto_20190616_0349'),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=200)),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=18)),
                ('keep_inventory', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='IncomeProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('profit', models.DecimalField(decimal_places=2, max_digits=18)),
                ('income', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taekonline.Income')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taekonline.Product')),
            ],
        ),
        migrations.AddField(
            model_name='income',
            name='products',
            field=models.ManyToManyField(through='taekonline.IncomeProduct', to='taekonline.Product'),
        ),
        migrations.AddField(
            model_name='income',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='taekonline.Student'),
        ),
    ]
