# Generated by Django 2.2.1 on 2019-06-18 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taekonline', '0016_product_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='products',
        ),
        migrations.AlterField(
            model_name='incomeproduct',
            name='profit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
    ]
