# Generated by Django 2.2.1 on 2019-06-18 18:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('taekonline', '0017_auto_20190618_1820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='date',
        ),
        migrations.AddField(
            model_name='income',
            name='income_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='income',
            name='income_time',
            field=models.TimeField(auto_now=True),
        ),
    ]
